language: clojure
install: cd leiningen-core; lein test, install; cd ..
script: bin/lein test
branches:
  only:
    - 1.x
    - master
notifications:
  irc: "irc.freenode.org#leiningen"
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
