---
before_script: mkdir -p leiningen-core/lib; curl -o leiningen-core/lib/lc.jar p.hagelb.org/lein-core-2-snap-standalone.jar
script: bin/lein test
branches:
  only:
    - 1.x
    - master
notifications:
  irc: "irc.freenode.org#leiningen"